use_frameworks!

target 'IOSBaseKit_Example' do
  pod 'IOSBaseKit', :path => '../'

  target 'IOSBaseKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
